version: '2'

services:

  elasticsearch:
    build: elasticsearch/
    ports:
      - 9200:9200
      - 9300:9300

  logstash:
    build: logstash/
    ports:
      - 5000:5000
    depends_on:
      - elasticsearch

  kibana:
    build: kibana/
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch